name: paymentmicroservice sync action

on:
  workflow_dispatch:
  push:
    branches:
      - test
permissions:
  id-token: write
  contents: read
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/paymentmicroservice:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/paymentmicroservice:latest
            docker stop paymentmicroservice || true
            docker rm paymentmicroservice || true
            docker run -d --name paymentmicroservice -p 3010:3010 ${{ secrets.DOCKER_HUB_USERNAME }}/paymentmicroservice:latest 

